version: '3'

services:
  react:
    build:
        context: ./react_dir
        dockerfile: react_Dockerfile
    container_name: react_app
    volumes:
        - ./react_dir:/app
    ports:
        - 3000:3000
    tty: true
    stdin_open: true

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql_host
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: qiita_rank
        MYSQL_USER: user
        MYSQL_PASSWORD: userpass
        TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
        - ./db-data:/var/lib/mysql
    ports:
            - 3306:3306
    restart: always
